version: "3.9"

services:
  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    volumes:
      - ./wordpress:/var/www/html
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${APP_NAME}_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - php
  mysql:
    image: "mysql:latest"
    container_name: ${APP_NAME}_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: